try with rename and link

diff --git a/.github/workflows/chrome-test.yaml b/.github/workflows/chrome-test.yaml
--- a/.github/workflows/chrome-test.yaml
+++ b/.github/workflows/chrome-test.yaml
@@ -15,9 +15,8 @@ jobs:
           chrome-version: stable
       - name: Add chrome to PATH
         run: |
-          mkdir --parents $HOME/.local/bin
-          ln -s ${{ steps.setup-chrome.outputs.chrome-path }} $HOME/.local/bin/google-chrome
-          echo "$HOME/.local/bin" >> $GITHUB_PATH
+          test -f /usr/bin/google-chrome && mv /usr/bin/google-chrome /usr/bin/google-chrome-ori || echo "/usr/bin/google-chrome not found"
+          ln -s ${{ steps.setup-chrome.outputs.chrome-path }} /usr/bin/google-chrome
       - name: Build
         run: |
           env | sort
