chore: release version check

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -50,6 +50,11 @@ jobs:
              | tee -a  $GITHUB_STEP_SUMMARY
             exit 1
           fi
+          if [[ ! "${{ inputs.version }}" = "${{ inputs.target-branch }}."* ]]; then
+            echo "ERROR: Invalid version specified: '${{ inputs.version }}' does not match the release branch ${{ inputs.target-branch }}." \
+             | tee -a  $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
           if git rev-parse -q --verify "refs/tags/${{ inputs.version }}" >/dev/null; then
             echo "Version ${{ inputs.version }} already exists. Please choose a different version." \
              | tee -a  $GITHUB_STEP_SUMMARY
