chore: copy release workflow from main

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -6,6 +6,15 @@ on:
         description: "Version to release (e.g. 1.1.0 or 1.2.0.alpha1)"
         required: true
         type: string
+      target-branch:
+        description: "Branch to release"
+        required: true
+        type: choice
+        default: 'main'
+        options:
+        - main
+        - 2.0
+        - 1.0
       dry-run:
         description: "Dry run (Skips remote operations)"
         required: true
@@ -17,6 +26,20 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Validate Workflow branch
+        run: |
+          BRANCH_NAME=${GITHUB_REF##*/}
+          if [[ "main" != "${BRANCH_NAME}" ]]; then
+            echo "ERROR: Release Workflow must be dispatched on 'main' branch."
+            exit 1
+          fi
+
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          ref: refs/heads/${{ inputs.target-branch }}
+          fetch-depth: 0
+
       - name: Validate version
         run: |
           VERSION_REGEX='^[0-9]+\.[0-9]+\.[0-9]+(\.(alpha|beta|rc)[0-9]+)?$'
@@ -24,45 +47,39 @@ jobs:
             echo "ERROR: Invalid version specified: '${{ inputs.version }}'. Please enter a valid SemVer version, like '1.2.3' or '1.0.0.alpha1'."
             exit 1
           fi
-
-      - name: Check Branch
-        run: |
-          ALLOWED_BRANCHES=("main" "1.0" "2.0")
-          BRANCH_NAME=${GITHUB_REF##*/}
-          if [[ ! " ${ALLOWED_BRANCHES[@]} " =~ " ${BRANCH_NAME} " ]]; then
-            echo "ERROR: Branch ${BRANCH_NAME} is not allowed. Only branches $(IFS=,; echo "${ALLOWED_BRANCHES[*]}") are allowed."
+          if git rev-parse -q --verify "refs/tags/${{ inputs.version }}" >/dev/null; then
+            echo "Version ${{ inputs.version }} already exists. Please choose a different version."
             exit 1
           fi
 
-      - name: Checkout
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
+#      - name: Check Branch
+#        run: |
+#          ALLOWED_BRANCHES=("main" "1.0" "2.0")
+#          BRANCH_NAME=${GITHUB_REF##*/}
+#          if [[ ! " ${ALLOWED_BRANCHES[@]} " =~ " ${BRANCH_NAME} " ]]; then
+#            echo "ERROR: Branch ${GITHUB_REF} is not allowed. Only branches $(IFS=,; echo "${ALLOWED_BRANCHES[*]}") are allowed."
+#            exit 1
+#          fi
 
-#      - name: Setup Java
-#        uses: actions/setup-java@v3
-#        with:
-#          java-version: 17
-#          distribution: 'temurin'
-#          server-id: central
+      - name: Setup Java
+        uses: actions/setup-java@v3
+        with:
+          java-version: 17
+          distribution: 'temurin'
 
       - name: Staging artifacts
-        env:
-          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.MAVEN_GPG_PUBLIC_KEY }}
-          JRELEASER_GPG_SECRET_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
-          JRELEASER_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
         run: |
-          echo mvn -Pdistribution deploy -DaltDeploymentRepository=local::file:./target/staging-deploy
+          mvn -V -ntp -Pdistribution deploy -Drevision=${{ inputs.version }} -DaltDeploymentRepository=local::file:./target/staging-deploy
 
       - name: Run JReleaser
         env:
           JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           JRELEASER_DEPLOY_MAVEN_ARTIFACTORY_TOKEN: ${{ secrets.JFROG_TOKEN }}
-          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.MAVEN_GPG_PUBLIC_KEY }}
-          JRELEASER_GPG_SECRET_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
-          JRELEASER_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
+          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
+          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
+          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
         run: |
-          echo mvn -Pdistribution -Djreleaser.dry.run="${{ github.event.inputs.dry-run }}" jreleaser:full-release 
+          mvn -V -ntp -Pdistribution  -Drevision=${{ inputs.version }} -Djreleaser.dry.run="${{ github.event.inputs.dry-run }}" jreleaser:full-release 
 
       - name: JReleaser release output
         if: always()
@@ -70,5 +87,5 @@ jobs:
         with:
           name: jreleaser-release
           path: |
-            out/jreleaser/trace.log
-            out/jreleaser/output.properties
+            target/jreleaser/trace.log
+            target/jreleaser/output.properties
