chore: try release

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -24,13 +24,17 @@ jobs:
             echo "ERROR: Invalid version specified: '${{ inputs.version }}'. Please enter a valid SemVer version, like '1.2.3' or '1.0.0.alpha1'."
             exit 1
           fi
+          if git rev-parse -q --verify "refs/tags/${{ inputs.version }}" >/dev/null; then
+            echo "Version ${{ inputs.version }} already exists. Please choose a different version."
+            exit 1
+          fi
 
       - name: Check Branch
         run: |
           ALLOWED_BRANCHES=("main" "1.0" "2.0")
           BRANCH_NAME=${GITHUB_REF##*/}
           if [[ ! " ${ALLOWED_BRANCHES[@]} " =~ " ${BRANCH_NAME} " ]]; then
-            echo "ERROR: Branch ${BRANCH_NAME} is not allowed. Only branches $(IFS=,; echo "${ALLOWED_BRANCHES[*]}") are allowed."
+            echo "ERROR: Branch ${GITHUB_REF} is not allowed. Only branches $(IFS=,; echo "${ALLOWED_BRANCHES[*]}") are allowed."
             exit 1
           fi
 
@@ -39,12 +43,11 @@ jobs:
         with:
           fetch-depth: 0
 
-#      - name: Setup Java
-#        uses: actions/setup-java@v3
-#        with:
-#          java-version: 17
-#          distribution: 'temurin'
-#          server-id: central
+      - name: Setup Java
+        uses: actions/setup-java@v3
+        with:
+          java-version: 17
+          distribution: 'temurin'
 
       - name: Staging artifacts
         env:
@@ -52,7 +55,7 @@ jobs:
           JRELEASER_GPG_SECRET_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
           JRELEASER_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
         run: |
-          echo mvn -Pdistribution deploy -DaltDeploymentRepository=local::file:./target/staging-deploy
+          mvn -Pdistribution deploy -Drevision=${{ input.version }} -DaltDeploymentRepository=local::file:./target/staging-deploy
 
       - name: Run JReleaser
         env:
@@ -62,7 +65,7 @@ jobs:
           JRELEASER_GPG_SECRET_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
           JRELEASER_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
         run: |
-          echo mvn -Pdistribution -Djreleaser.dry.run="${{ github.event.inputs.dry-run }}" jreleaser:full-release 
+          mvn -Pdistribution  -Drevision=${{ input.version }} -Djreleaser.dry.run="${{ github.event.inputs.dry-run }}" jreleaser:full-release 
 
       - name: JReleaser release output
         if: always()
